# Generated by Django 3.1.5 on 2021-01-14 12:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210114_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, editable=False),
        ),
    ]
