# Generated by Django 3.1.5 on 2021-01-15 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_chatmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_members',
            field=models.ManyToManyField(related_name='RoomMembers', to=settings.AUTH_USER_MODEL),
        ),
    ]
