# Generated by Django 3.1.5 on 2021-01-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_room_room_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_text_send_at',
            field=models.DateTimeField(null=True),
        ),
    ]
