# Generated by Django 3.1.5 on 2021-01-18 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_room_last_text_send_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='last_text_send_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
