# Generated by Django 3.1.5 on 2021-01-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20210118_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmodel',
            options={'ordering': ['-added_on']},
        ),
    ]
