# Generated by Django 3.1.5 on 2021-02-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210121_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
